sudo: required
services:
- docker
env:
  global:
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl
- docker run --name mongo -p 27017:27017 -d mongo:3.2
- sleep 30s
- npm install
install:
- docker build -t cloudboost/analytics:2.0.$TRAVIS_BUILD_NUMBER .
- docker run --name analytics -e LOG_TOKEN='c064fc7e-4fc6-41e6-b51f-32c30deafdcc' -p 5555:5555 -it --link mongo:mongo -d cloudboost/analytics:2.0.$TRAVIS_BUILD_NUMBER
- sleep 30s
- curl http://localhost:5555/status
after_success:
# Build Docker Images
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t cloudboost/analytics:latest .;
  fi
# Docker Deploy for staging builds
- if [ "$TRAVIS_BRANCH" == "staging" ]; then
    docker build -t cloudboost/analytics:staging .;
    docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL;
    docker push cloudboost/analytics:staging;
    git clone https://github.com/CloudBoost/kube-cred.git;
    cd kube-cred;
    openssl enc -in config.enc -out config -d -aes256 -k $KUBE_ENC;
    mkdir ~/.kube;
    mv config ~/.kube/;
    kubectl rolling-update cloudboost-analytics-staging --image=cloudboost/analytics:staging --image-pull-policy=Always;
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/""$cloudflare_zone""/purge_cache" -H "X-Auth-Email:hello@cloudboost.io" -H "X-Auth-Key:""$cloud_flare_key" -H "Content-Type:application/json" --data "{'purge_everything':true}";
  fi
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=2.0.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITLOGIN@github.com/CloudBoost/analytics --tags
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "README.md"
  skip_cleanup: true
  on:
    tags: false
    branch: master
after_deploy:
# Docker Deploy.
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL;
  docker push cloudboost/analytics:2.0.$TRAVIS_BUILD_NUMBER;
  docker push cloudboost/analytics:latest;
  git clone https://github.com/CloudBoost/kube-cred.git;
  cd kube-cred;
  openssl enc -in config.enc -out config -d -aes256 -k $KUBE_ENC;
  mkdir ~/.kube;
  mv config ~/.kube/;
  kubectl rolling-update cloudboost-analytics --image=cloudboost/analytics:latest --image-pull-policy=Always;
  fi
branches:
  except:
    - /^*-v[0-9]/
#Notify Team on Slack
notifications:
  slack: cloudboost:gm7nWJDLDtBRyF75VKLKOoMW
